run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  govet:
    # check-shadowing: true  # Deprecated - use enable: shadow instead
    enable:
      - shadow
    disable:
      - fieldalignment  # フィールドの順序による最適化は一旦無視
  gocyclo:
    min-complexity: 20  # 複雑度の閾値を緩和
  goconst:
    min-len: 3
    min-occurrences: 3
  goimports:
    local-prefixes: github.com/todotui
  mnd:  # gomndの代わりにmndを使用
    settings:
      checks: argument,case,condition,operation,return,assign
      ignored-numbers: 0,1,2
      ignored-functions: strings.SplitN
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam  # 重いパラメータのチェックを無効化
      - rangeValCopy  # rangeでのコピーチェックを無効化
      - evalOrder  # 評価順序のチェックを無効化
  funlen:
    lines: 150  # 関数の長さを緩和
    statements: 80
  misspell:
    locale: US
  lll:
    line-length: 140
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  whitespace:
    multi-if: false
    multi-func: false
  wsl:
    # WSLルールを大幅に緩和
    strict-append: false
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-case-trailing-whitespace: true
    allow-cuddle-declarations: true
    allow-trailing-comment: true
    force-case-trailing-whitespace: 0

linters:
  disable-all: true
  enable:
    # 必須のエラー検出linter（高速）
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # 基本的なコードスタイルlinter（高速）
    - gofmt
    - goimports
    - misspell
    
    # セキュリティlinter（必要最小限）
    - gosec
    
    # 軽量なlinter
    - unconvert
    - asciicheck
    - goprintffuncname
    
    # 重いlinterは無効化（開発時のみ使用）
    # - revive      # 重い
    # - whitespace  # 重い
    # - prealloc    # 重い
    # - unparam     # 重い
    # - gochecknoinits  # 重い
    # - gochecknoglobals # 重い
    # - goconst     # 重い
    # - gocritic    # 重い
    # - gocyclo     # 重い
    # - mnd         # 重い
    # - nakedret    # 重い
    # - nestif      # 重い
    # - funlen      # 重い

issues:
  exclude-dirs:
    - vendor
    - .git
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
  uniq-by-line: true
  exclude-rules:
    # テストファイルでの一部のlinterを無効化
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gochecknoglobals
        - lll
        - unused
    
    # main関数での一部のlinterを無効化
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals
        - gocyclo  # main関数は複雑になりがち
    
    # UI/View関連ファイルでのマジックナンバーを許可
    - path: internal/ui/
      linters:
        - mnd  # UI関連の数値定数は可読性のため許可
        - gocyclo  # UI関連は複雑になりがち
        - nestif  # UI関連のネストは複雑になりがち
        - funlen  # UI関連の関数は長くなりがち
        - gochecknoglobals  # UI関連のグローバル変数は許可
        - ineffassign  # UI関連の非効率的な代入は許可
        - staticcheck  # UI関連のstaticcheckエラーを許可
    
    # 生成されたファイルを除外
    - path: ".*\\.pb\\.go"
      linters:
        - gochecknoglobals
        - lll
        - misspell
    
    # 特定のエラーメッセージを除外
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "should have a package comment"
      linters:
        - revive
    - text: "stutters"
      linters:
        - revive
    - text: "unused-parameter"
      linters:
        - revive
    
    # os.Exit関連のエラーを除外（main関数では適切）
    - text: "exitAfterDefer"
      path: cmd/
      linters:
        - gocritic
    
    # Shadow変数のエラーを特定ケースで除外
    - text: "shadow:"
      path: _test\.go
      linters:
        - govet
  
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - revive
      severity: warning 