version: 1

project_name: todotui

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/todotui
    binary: todotui
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/yuucu/todotui/pkg/app.version={{.Version}}
      - -X github.com/yuucu/todotui/pkg/app.commit={{.Commit}}
      - -X github.com/yuucu/todotui/pkg/app.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE
      - sample-config.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  disable: false
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: '🚨 Breaking Changes'
      regexp: '^.*?BREAKING CHANGE.*?$'
      order: 0
    - title: '🚀 New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: '📚 Documentation'
      regexp: '^.*?docs?(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: '🏗️ Maintenance'
      regexp: '^.*?(chore|refactor|style)(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: '📦 Dependencies'
      regexp: '^.*?(deps?|dependency)(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: '⚡ Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: 'Others'
      order: 999

release:
  github:
    owner: yuucu
    name: todotui
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} {{.Tag}}"
  header: |
    ## 🚀 What's Changed in {{.Tag}}
    
    Download the latest release for your platform below.
    
    ### 📥 Quick Installation
    ```bash
    # Go install (recommended for latest version)
    go install github.com/yuucu/todotui/cmd/todotui@{{.Tag}}
    ```
  footer: |
    **Full Changelog**: https://github.com/yuucu/todotui/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ## 📥 Installation Options
    
    ### Binary Download
    1. Download the appropriate binary for your platform from the assets above
    2. Extract the archive: `tar -xzf todotui_*.tar.gz` (or unzip for Windows)
    3. Move the binary to your PATH: `sudo mv todotui /usr/local/bin/` (Unix-like systems)
    
    ### Go Install
    ```bash
    # Install latest stable version
    go install github.com/yuucu/todotui/cmd/todotui@latest
    
    # Install specific version
    go install github.com/yuucu/todotui/cmd/todotui@{{.Tag}}
    ```
    
    ### Package Managers (Coming Soon)
    ```bash
    # Homebrew (planned)
    brew install yuucu/tap/todotui
    ```
    
    ## 🚀 Getting Started
    
    After installation, run:
    ```bash
    todotui --help
    ```
    
    For configuration and usage examples, see our [documentation](https://github.com/yuucu/todotui#readme).

# Homebrew configuration for future use
brews:
  - repository:
      owner: yuucu
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/yuucu/todotui
    description: "A clean, efficient terminal-based todo manager that respects the todo.txt format"
    license: MIT
    skip_upload: auto
    dependencies:
      - name: git
    test: |
      system "#{bin}/todotui", "--version"
    install: |
      bin.install "todotui"

# Universal Binaries for macOS
universal_binaries:
  - replace: true

announce:
  skip: '{{gt .Patch 0}}' 