# Everforest Light Theme Test Configuration

# =====================================
# Theme Settings - Everforest Light
# =====================================
theme: everforest-light

# =====================================
# Priority Level Settings
# =====================================
priority_levels:
  - ""    # No priority
  - A     # Highest priority
  - B     # High priority
  - C     # Medium priority
  - D     # Low priority

# =====================================
# File Settings
# =====================================
default_todo_file: ./sample.todo.txt

# =====================================
# UI Settings
# =====================================
ui:
  left_pane_ratio: 0.33
  min_left_pane_width: 18
  min_right_pane_width: 28
  vertical_padding: 2

# =====================================
# Logging Settings
# =====================================
logging:
  enable_debug: false
  log_file_path: ""
  max_log_days: 7 