# Todo TUI Configuration File
# Configuration file location: ~/.config/todotui/config.yaml

# =====================================
# Theme Settings
# =====================================
# Available themes: catppuccin, nord, everforest-dark, everforest-light
theme: catppuccin

# =====================================
# Priority Level Settings
# =====================================
# First empty string ("") represents no priority (required)
priority_levels:
  - ""    # No priority
  - A     # Highest priority
  - B     # High priority
  - C     # Medium priority
  - D     # Low priority

# =====================================
# File Settings
# =====================================
# Default todo.txt file path
default_todo_file: ./sample.todo.txt

# =====================================
# UI Settings
# =====================================
ui:
  # Layout settings
  left_pane_ratio: 0.33        # Left pane width ratio (0.1-0.9)
  min_left_pane_width: 18      # Minimum left pane width
  min_right_pane_width: 28     # Minimum right pane width
  vertical_padding: 2          # Vertical padding (1-5)

  # Completed task transition settings
  completed_task_transition:
    # Number of days to wait before moving completed tasks to "Completed Tasks" filter
    delay_days: 1              # Default: 1 day (0 for immediate move)
    
    # Time of day (24-hour format) when the transition should occur
    transition_hour: 5         # Default: 5 (05:00 morning)

# =====================================
# Logging Settings
# =====================================
# Log files are always created for troubleshooting
logging:
  # Debug mode - shows detailed internal operations
  enable_debug: false

  # Custom log file path (leave empty for OS-specific default)
  # macOS: ~/Library/Logs/todotui/todotui-YYYY-MM-DD.log
  # Linux: ~/.local/share/todotui/logs/todotui-YYYY-MM-DD.log
  # Windows: %APPDATA%/todotui/logs/todotui-YYYY-MM-DD.log
  log_file_path: ""

  # Number of days to keep log files (automatic cleanup)
  max_log_days: 30
