# todotui 設定ファイル (ログ設定あり)
# ~/.config/todotui/config.yaml に配置してください

# テーマ設定
theme: "catppuccin"  # catppuccin, nord

# 優先度レベル（空文字列は優先度なしを表す）
priority_levels:
  - ""
  - "A"
  - "B"
  - "C"
  - "D"

# デフォルトのTODOファイルパス（~は自動展開されます）
default_todo_file: "~/todo.txt"

# UI設定
ui:
  # 左ペインの幅比率（0.0〜1.0）
  left_pane_ratio: 0.33
  
  # 最小ペイン幅
  min_left_pane_width: 18
  min_right_pane_width: 28
  
  # 垂直パディング
  vertical_padding: 2

# ログ設定
logging:
  # デバッグログを有効にする
  enable_debug: false
  
  # ファイルにログを出力する
  output_to_file: true
  
  # カスタムログファイルパス（空の場合はデフォルトパスを使用）
  # macOS: ~/Library/Logs/todotui/todotui-YYYY-MM-DD.log
  # Linux: ~/.local/share/todotui/logs/todotui-YYYY-MM-DD.log
  # Windows: %APPDATA%/todotui/logs/todotui-YYYY-MM-DD.log
  log_file_path: ""
  
  # ログファイルを保持する日数
  max_log_days: 30 