# Todo TUI Configuration File
# 設定ファイルの場所: ~/.config/todotui/config.yaml

# =====================================
# テーマ設定
# =====================================
# 利用可能なテーマ: catppuccin, nord, default
theme: catppuccin

# =====================================
# 優先度レベル設定
# =====================================
# 最初の空文字("")は優先度なしを表す（必須）
priority_levels:
  - ""    # 優先度なし
  - A     # 最高優先度
  - B     # 高優先度
  - C     # 中優先度
  - D     # 低優先度

# =====================================
# ファイル設定
# =====================================
# デフォルトのtodo.txtファイルのパス
default_todo_file: ~/todo.txt

# =====================================
# UI設定
# =====================================
ui:
  # レイアウト設定
  left_pane_ratio: 0.33        # 左ペインの幅比率 (0.1-0.9)
  min_left_pane_width: 18      # 左ペイン最小幅
  min_right_pane_width: 28     # 右ペイン最小幅
  vertical_padding: 2          # 垂直パディング (1-5) 